language: python
python:
- '3.9'
services:
- mysql
before_install:
  - sudo mysql -u root --password="" < travis.sql
install:
- pip install -r requirements.txt
env:
  matrix:
  - Channel_ID=827598982020071487 Target_ID=827137883357708288
  global:
  - secure: 2e2m0Z1h5HzZxuV/GSZogT/rxCTM+go8ZmxF34A2Y+xLKWolyCLzkolvHOv/DIWd8GvlC3tGkwO4zRpyV/RiEcjv+99Xm2KY1GIBls2ki5wVHdC0YECU2UXl1zgTnsM8g+MhE51g+3F22OB6M3kzt6DEfviSvaZOK+lmubkC0FSDL7AGHUGKRx2K+LK5ISAy2uBcYqEaoBec0p4EsayrIv31UhI3y02QHrMCb6OK6xP/km54z4waDZEykHBM0O1F1m2nK5wevfzQBQB5EMZY9O/OFK57QdAWQMVejstlcjcXnOQ4U4jpvPzxkPhP9vCdttXAaFbdqc8Sm28rt33dC/s0fCu9mMYIx1GMv9vbH33vboGWDluOohpkhj3edxLwBEEtRGNPdqh9u5lNywIR0EvMH3tx5V75DN/ufb+GuZi/wEwMjJBphw2Yk6AvMkuA6zsHaJv7InopNdLO2NFl6jMbjRN981SjjrYt4nowbFMMNiqOe5fr4o4SCFE7XKRP9h612vec5mjODBXrseqa3uuUCfHaumeB5o6DXmrg+rCrfEOT3SGPdwwHfN4j6DuOo9epLX0P6kzmAwEkSyO2tJZGsQnGvtDXWodrqjDDJzT/WqK3nq3Beseu+46/2FeYDRpNXqOtBbwwCCtgR/V0mdXE864HbqKWKGV9cC2VFoY=
  - secure: SzP8qvRdIcZUh3g+/Wya9lsz8F4LCQNefMurrjmP+eu0xDMNAJM1ZwyTOlu6OyGqrMZsBh2O07efGkSTxPdPwUAV98crud0wd9zQ47aOEHnonPW2KCmA2dqGFZSsnPASXS+2pt0aC6hAJ/poaftbJweJWNhCdHwEHFDSWqC7w+dFtw0hcQbXgvxDyoX/P/gGg/KDca7OgeyTNzZxuZbGp2r0Du6DExA7r0al9AY8ZeARTJswAkv7NASsV6RD9fpqNiaze6fxN78nFO4mcXc5h3aywYc6xxPC2PWlGLmhlVmwld902irteZB9WU0VC5VTc6dcEoHH/9hYY+a4YuwquySXAhRrG2a+Y6lv0h1A7KfVmOYhLNdi44gQjOtkT/PRdNkHcWLU4KaEpAWZlPy/lTzC7AGIZyfnWUC2o26i+w4P3JmcBOCcz+fxAgVzr+7d11cM74GcixBqgqxs2CDzoiYGNMrxYV+mHLrhvFO7Vh7e/BWQbGKYNhIsJnKFaTdOGP9PCFyT7js3GnxYUgD8VvMEhGPm43rk8VYWkXaviu0zLpuYz7nNEhNYIOLuxtnqL2frQzPalBbcibE5zBhpwiv7IQAeqjjQkMGue3j3sgw2DG+Q/0MSjj1GXZNopL249L0f0mLBdKBnxKRNFPc5KI9Gr/1n/zo2mBvELIxwvz0=
script:
  - bash run_test.sh
after_success:
  - coveralls
