language: python
python:
- '3.9'
install:
- pip install -r requirements.txt
script:
- bash run_test.sh
env:
  matrix:
  - Channel_ID=827598982020071487 Target_ID=827137883357708288
  global:
  - secure: xjDDkEskic2mToEqPPzujM4/rU5MHZMHiVgJJ2BkzBV3bvviRJb78ODUpY2YUGlulH6NoivxPIP+qoQ4dPiHNezjQwR0LnvLJMPios2LIgnKqRmTdwVlZXkTWQTrMG+BeGmH65jk/dj5BKCHzisbnJQDjsxqHn3quBFYFDP6b+lh8JHh3WDF+vAjM6A2e8HnpKK0bLGI3/zphxh5CON3t0XiQ+1xtYC1N2D8hwLfusGtro1pWlRrst7+N6AKBNc3J0ScxRdFP5ee59ko/dQ/qKLJYa9msLHaWItIiiWPUesZJFH1ETiPhYI4CPx8bWAOPfuociFjWgsAXHbjSgVMd+U11Xl8s/+1li4NEaO86amZfAVyJC793+Y2TMIvqZhApRzcXrppoBg/EzwESsfoTybg8ItnfaXSADg6vHjrzKZRBS5YJ2Y7aobMCKFR/bDSqwxG8uO+JDQTzHUc+5bPBUMAAYafXnUE6kJJ+37Q//iNlimzTUo+INd3sChPRJZnrpdRWUMfogqi6esWWS7mZLXnx4x7nX6FID4H4Hkz8gldxLuE0otZ3cwH96iKi7Dc8lHtEUlzNjJJlVHsOzO2jYgzEBGHB8hcsz19cp0IqziqUKKmSkllQDzw5fYh0cdWEHQKmRWEOUcKtwWb6fsuzlxfZsPcVXwJlWdCFBqpTwc=
  - secure: j7QHLUTCutgNxdly2996dSI75wBz3/VqhC3VmUOyxKMx7Hm3SrFJk4dlQqlVoNXLxKWMRwi6CWZ5Pbndgcx6qW8qPqgn20lynZUzCltTdhcxBHb6JHHLLKXK0PXl8QJWzHCf8LYR0FJwgtNm5XcCSoAcJwPaRsm2m0Yj9JmzuGxQeLfbDgKOuOtn+9fP123cqICTj9ScP8QY0OB44i81S3OP81yuaVRTHpEwwWD5XwFzmmoWGDCfIEhxz5iw200U4XMgBnZrLwr9fX+J5mltCiW1/gAm6I6kaEGUZPk8LGVS00dzWUIzB6kaa77OEaWGCjE3m3Oaw3xfFiSMUTQHzjPvEbIZeA+5BdGXkCj0/uX4hrPBH9Tn6BL+Ynl6GTGMZypLj2ncgza0AP5tU2gugfgxHIMMIBjCmSgdL/SoQhy03EmL2t/ikh0gXmTaVDl2xqDmly5wXwBjMVqHmvSYg5qleXXjp0bXGWj8xqURD/gN4LUiI0whcfudIw+MfDQ9o3XaQRdxZpnKpYso0KoBglHHhgxKcJ1NVSNGDUxmMkwgFYLw1v2HnMcG5XCqaiFOMxEvGnr6Mep5PFu1b4Dl2BWDM9w3u/g85lklV/rUmk8cAMJkCIwCP3FnXSudauLoh/cW6PuCodbT77ejtIEUBLRuNN2nzwLe2NqTfT9+obM=
