language: python
python:
- '3.9'
install:
- pip install -r requirements.txt
env:
  matrix:
  - Channel_ID=827598982020071487 Target_ID=827137883357708288
  global:
  - secure: hHaWhPFMcIvgMFJbk1kKQmskFx1ICmbR6i9rtpFXQDQs5qrE4BhQhKh5dKpsi0QTxsyuzu4VF3uFiDHMSWUGTFrDG+XlRLCmyX/A6jLWqNcvFfYlKLLPOEiHHYcpzfRk5B5Ut+kEDOM39gEmIbPVOvC/t1+VSx5SqH0kaqMdqH0JV9VblFHYUU+6uvyn+1Dp4LXhmJn/B8gr4OlIGYw4/G9LsAHCQo2X9kThi7s59zvdcOrdDonFGOXDBVsvckpHPuZh/DU3Aosb+1vZzrS0QxhO4CL51CTYZavDo1tteP5HbbaWAv88cgj/13K4KXSM+DmL02gazfH/nnQlZg9f1AgB942GYgM4m8QHgGwaEzqWjlYiyMdQJadzCJgTKdYj5fY6DN35gT2ktRESHWC1Dnhww/lh5tHtxlJTlUCdcMYPQpqdkFpg5JOKtZ1EolcrRFowjknnNl94lYZ+DrpHBXjHlcNHZtKQg3KfS7muQrSWzljYOYhy1dXyqRIdIDZVXoGc+OX2A1mISPLG3mJI0tAriCPkdhA0UoNt63GVAKoMx1sbUrA33Ab6hiKFiPQM5jGxKMTkF6JvOctWFvYyRxR8Mnne/ewKQZPQlpFQ9RNTDMH9qAyxsWOnO1+U09eU9tAZmWwH7PXI1cK8oLiEUtZlOQvvkkjVLGOVOYRo1qg=
  - secure: SzP8qvRdIcZUh3g+/Wya9lsz8F4LCQNefMurrjmP+eu0xDMNAJM1ZwyTOlu6OyGqrMZsBh2O07efGkSTxPdPwUAV98crud0wd9zQ47aOEHnonPW2KCmA2dqGFZSsnPASXS+2pt0aC6hAJ/poaftbJweJWNhCdHwEHFDSWqC7w+dFtw0hcQbXgvxDyoX/P/gGg/KDca7OgeyTNzZxuZbGp2r0Du6DExA7r0al9AY8ZeARTJswAkv7NASsV6RD9fpqNiaze6fxN78nFO4mcXc5h3aywYc6xxPC2PWlGLmhlVmwld902irteZB9WU0VC5VTc6dcEoHH/9hYY+a4YuwquySXAhRrG2a+Y6lv0h1A7KfVmOYhLNdi44gQjOtkT/PRdNkHcWLU4KaEpAWZlPy/lTzC7AGIZyfnWUC2o26i+w4P3JmcBOCcz+fxAgVzr+7d11cM74GcixBqgqxs2CDzoiYGNMrxYV+mHLrhvFO7Vh7e/BWQbGKYNhIsJnKFaTdOGP9PCFyT7js3GnxYUgD8VvMEhGPm43rk8VYWkXaviu0zLpuYz7nNEhNYIOLuxtnqL2frQzPalBbcibE5zBhpwiv7IQAeqjjQkMGue3j3sgw2DG+Q/0MSjj1GXZNopL249L0f0mLBdKBnxKRNFPc5KI9Gr/1n/zo2mBvELIxwvz0=
script:
  - coverage run src/bot.py -t &
  - sleep 5s
  - python src/tests/test_basic.py -c "$Channel_ID" --run all "$Target_ID" "$Tester"
  - coverage report
after_success:
  - coveralls
