language: python
python:
- '3.9'
install:
- pip install -r requirements.txt
script:
- run_test.sh
env:
    Channel_ID = 827598982020071487
    Target_ID = 827137883357708288
  global:
  - secure: 0jT146TZpQBkX5QqPNO1/pbyU3NFmd4CtBpLlGTp/DIysoD6yK079Dw+QudNTPXl1r4Sv3HvoM4pv/z0VBz5f7bNj4WGnBA6l8if921f0mqAvoetKYSuIZ8vqAa/lHo8rbbOwcd9dFul/uMst/qireVmxD4EkTSKBFuKKeEguGidJlde/YpXukP8zmc1/DvXGL0yqcTymLhL9OeldVcUwloeNSuDmximf9mmwCdqcmaOEuwxM7sJOhcHWxRhKilEoHo5Kby2+dXS8ksjJtZJ2FoKqXjKWRd5fNtPrIXKdU/INkbYSqG5efNQYiRxXaXi5W4WER7BSX0HvT4PPi6e4BuMo3qFsgl+v/eZq3rKdR2xlUGIzP+CwVmGnv4BsSm/zukK1lqBY2gd47x2M9f79/cmoN1zw3rzhPr42r4umFM5eL0AoaaUpnD8W1qXrqNibr/euHdbo7f4GfX7OOj4ltWHWd1Oi5hVn+ItRuiI+rpnjXtIP1Hb8Wu1jLlucKgfayLOF3oKWnqIHfYAjmbZOpZVDOMoSpvSMoUw3c+EZQ2a31Old9A1PWj1aNMdQHLZntrESBJG7sJGt31n5r2bfAOdfsUTTrliQUjn0FcHTXSadzfJveTprc/JonQglOv9GdUOQ9OuLMifkf7yEyM2P1ATc+SUs1uG04QMXPWN0Ec=
  - secure: C1QJxEhFtjGl2fF/gLoZz2PSkKc707GgH7SdWAh8a/9qKh8tj7vwmdPb6rA5jeXluqNoltqAQMpt60/e75W+0phbJ5+KKWF+CuDETqTW+1y+ungwSnFm+LI9Td1omCMovmPepy38wCOB7iIGMWL/F29m8fDOBA28Pw7RicLa2TDVKp1aWN6aHKFLPp0Kkg4JLMjS1pTJlBxa6v7P5ZntofO4FuIUfOv8Jzkc0byHsTQTbJy/YiUDS4Emgn8+DwL75A7nEFr8tGQlbxib6nGz9WGyAX/P4pteuqXcMhfCNdii4/W+ouu27w+Q+mro2JVkIHmFfKWijsMj5VNvQeP/j1b7sYv3imwDgEhAxfjNLtFjTJRWSzDI4fAdqf2sJu9f5V8sR+VF4Dzo+B7lqfH1w84mJ4FV1lCoPxYKpuXX29fiVIDsSNyysYfmYXfQJ5aM/MxCja31gCt8fY/fiVpHqPkciIr58qzEHUBrINXh0UIVJ54j4NSMUCdIsvIp5xo1q7aH+3LL+2c8qiv4TGlcZh9bYcy48a3u//Rp4JVOP5PQ/nYb0QPMYSw+Bykc85LlVVO6QJKKBe4Aii2DV3Ej0ndP93Rna31/x5qJSQt2tvhR9WOSEJjslu+X/RfgHZZ1qxBDhj4CClC2+QCyastbnNsAgf8A7W20WrGMo7UYQsQ=
